import { useState } from "react";
import "./App.css";

function App() {
  const [screen, setScreen] = useState("welcome"); // "welcome" | "loading" | "results"
  const [data, setData] = useState(null);
  const [error, setError] = useState(null);

  const fetchAnalysis = async () => {
    setScreen("loading");
    setError(null);

    try {
      const response = await fetch("http://127.0.0.1:8000/analyze?year=2023");
      if (!response.ok) {
        throw new Error("Failed to fetch analysis");
      }
      const result = await response.json();
      setData(result);
      setScreen("results");
    } catch (err) {
      console.error(err);
      setError("Something went wrong. Please make sure the backend server is running.");
      setScreen("welcome");
    }
  };

  const handleFileChange = (e) => {
    const file = e.target.files[0];
    if (file) {
      console.log("File selected:", file.name);

      fetchAnalysis();
    }
  };

  const handleSampleData = () => {
    fetchAnalysis();
  };

  return (
    <div className="page">
      {screen === "welcome" && (
        <div className="welcome-card">
          <div className="icon-circle">📊</div>

          <h1>Welcome to FinSight</h1>
          <p className="subtitle">
            Upload a company's financial statement and get an instant,
            plain-language read on how healthy the business really is.
          </p>

          {error && <p className="error-message">{error}</p>}

          <label className="upload-box">
            <input
              type="file"
              accept=".csv"
              onChange={handleFileChange}
              hidden
            />
            <div className="upload-icon">📄</div>
            <p className="upload-title">Drop your CSV file here</p>
            <p className="upload-subtitle">or click to browse</p>
          </label>

          <div className="divider">
            <span>or</span>
          </div>

          <button className="sample-button" onClick={handleSampleData}>
            ✨ Try with sample company data
          </button>

          <p className="footer-note">
            Numbers are calculated with Pandas. Explanations are generated by AI.
          </p>
        </div>
      )}

      {screen === "loading" && (
        <div className="loading-card">
          <div className="spinner"></div>
          <p className="loading-title">Analyzing your data</p>
          <p className="loading-subtitle">
            Calculating ratios, then asking AI to explain them
          </p>
        </div>
      )}

     {screen === "results" && data && (
  <div className="results-card">
    <div className="results-header">
      <h2>Results for {data.year}</h2>
     <span className="health-badge">{data.verdict}</span>
    </div>

    <div className="ratios-grid">
      {Object.entries(data.ratios).map(([key, value]) => (
        <div className="ratio-card" key={key}>
          <div className="ratio-label">{key}</div>
          <div className="ratio-value">{value}</div>
        </div>
      ))}
    </div>

    <div className="ai-explanation-box">
      <div className="ai-label">AI Explanation</div>
      <p>{data.ai_explanation}</p>
    </div>
  </div>
)}
    </div>
  );
}

export default App;