import { useState } from "react";
import "./App.css";

function App() {
  const [loading, setLoading] = useState(false);

  const handleFileChange =  (e) => {
    const file = e.target.files[0] ;
    if(file) {
      console.log("File selected :",file.name);
    }
  } ;


  return (
    <div className="page">
      <div className="welcome-card">
        <div className="icon-circle">📊</div>

        <h1>Welcome to FinSight</h1>
        <p className="subtitle">
          Upload a company's financial statement and get an instant,
          plain-language read on how healthy the business really is.
        </p>

        <label className="upload-box">
          <input
            type="file"
            accept=".csv"
            onChange={handleFileChange}
            hidden
          />
          <div className="upload-icon">📄</div>
          <p className="upload-title">Drop your CSV file here</p>
          <p className="upload-subtitle">or click to browse</p>
        </label>

        <div className="divider">
          <span>or</span>
        </div>

        <button className="sample-button">
          ✨ Try with sample company data
        </button>

        <p className="footer-note">
          Numbers are calculated with Pandas. Explanations are generated by AI.
        </p>
      </div>
    </div>
  );
}

export default App;